name: CI Workflow

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: 2.4pre20210908_3c56f62
          nix_conf: experimental-features = nix-command flakes
      - run: nix build -L
      - run: nix flake check
      - run: nix copy .#devEnv --to 's3://nix/?scheme=https&endpoint=nyc3.digitaloceanspaces.com'
