name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: shopstic/deno:1.7.1
    steps:
    - uses: actions/checkout@v2
    - run: ./ci.sh