name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: shopstic/deno:1.8.1
    steps:
      - uses: actions/checkout@v2
      - run: ./ci.sh
