name: CI

on: [push]

defaults:
  run:
    shell: bash

jobs:
  determine-env:
    name: Determine environment
    runs-on: ubuntu-20.04
    outputs:
      name: ${{ steps.env.outputs.name }}
    steps:
      - id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=name::main"
          else
            echo "::set-output name=name::feature"
          fi

  build:
    name: Build 
    runs-on: ubuntu-20.04
    needs: determine-env
    environment:
      name: ${{ needs.determine-env.outputs.name }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup
        uses: shopstic/tailscale-nix-builder/setup@5d038bf4bfb3dea2f3b588efe6388796e263c6d4
        timeout-minutes: 1
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}
          nixCacheS3AccessKeyId: ${{ secrets.NIX_CACHE_S3_ACCESS_KEY_ID }}
          nixCacheS3SecretAccessKey: ${{ secrets.NIX_CACHE_S3_SECRET_ACCESS_KEY }}

      - name: Build dev env
        run: nix build -L -vv

      - name: Test
        run: nix develop -v -c ./ci.sh