name: Build

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build 
    runs-on: [self-hosted, nix, general, arm64-linux, small]
    environment:
      name: main
    steps:
      - uses: actions/checkout@v4

      - name: Build dev env
        run: nix build -L -v --no-link

      - name: Test
        shell: nix develop -v -c bash {0}
        run: |
          ./cli.sh code_quality
          ./cli.sh run_tests