name: Main Workflow

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
    environment:
      name: ${{ github.ref }}
    env:
      NIX_CACHE_S3: s3://nixed/cache?profile=nix-cache&scheme=https
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Create AWS credentials
        run: |
          mkdir -p ~/.aws
          cat <<EOF > ~/.aws/credentials
          [nix-cache]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = ${{ env.NIX_CACHE_S3 }} https://cache.nixos.org/
            trusted-users = root runner

      - name: Test
        run: nix develop -c ./ci.sh

      - name: Update nix cache
        if: github.ref == 'refs/heads/main'
        run: |
          nix copy .#devEnv --to '${{ env.NIX_CACHE_S3 }}' -v