name: Build

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build 
    runs-on: [self-hosted, nix]
    environment:
      name: main
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Build dev env
        run: nix build -L -v --no-link

      - name: Test
        run: nix develop -v -c ./ci.sh