name: Main Workflow

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref }}
    env:
      NIX_CACHE_S3: s3://nixed/cache?profile=nix-cache&scheme=https
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create AWS credentials
        run: |
          mkdir -p ~/.aws
          cat <<EOF > ~/.aws/credentials
          [default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: 2.4pre20210908_3c56f62
          nix_conf: |
            experimental-features = nix-command flakes
            substituters = ${{ env.NIX_CACHE_S3 }} https://cache.nixos.org/
            trusted-users = root runner
      - name: Test
        run: nix develop -c ./ci.sh
      - name: Update nix cache
        run: |
          nix copy .#devEnv --to '${{ env.NIX_CACHE_S3 }}' -v